### ISSUE TITLE
Version management for website

### ISSUE THREAD

**Issue by yorickdewid** [Zanhos/KCAF-Checklist#4]
Its hard to determine which version is now deployed online. This is often done by denoting the commit hash in the website. I'll show how this is done later. For now just glance over this issue and think of a few ways to do so.

**Comment by cenikk** [comment]
Hey, I've done some research on this part and came across [This Article](https://medium.freecodecamp.org/versioning-your-web-apps-38d9d1ccec05) from FreeCodeCamp. They also show a package that you can use for bundling your code if you use webpack ([Git revision webpack plugin](https://www.npmjs.com/package/git-revision-webpack-plugin)). I don't know if this will be of any use, but I'll see that on Monday :D.
